name: Python tests with Allure

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Обновите до v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install allure-pytest

    - name: Run tests
      run: |
        pytest --alluredir=./allure-results

    - name: Generate Allure report
      uses: simple-elf/allure-report-action@v1  # Правильное название
      if: always()
      with:
        allure_results: ./allure-results
        keep_history: true