name: Python tests with Allure

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest==8.4.1
        pip install selene==2.0.0rc9  # Последняя стабильная RC-версия
        pip install allure-pytest==2.13.2
        pip install webdriver-manager

    - name: Run tests
      run: |
        pytest -v --alluredir=./allure-results

    - name: Generate Allure report
      uses: simple-elf/allure-report-action@v1
      if: always()
      with:
        allure_results: ./allure-results
        keep_history: true